module.exports = [
  {
    _id: "62f2f7e68d171afc82b80bb6",
    index: 0,
    guid: "712e5b9a-4490-42e3-80e3-661a8f847948",
    isActive: true,
    balance: "$3,128.89",
    picture: "http://placehold.it/32x32",
    age: 40,
    eyeColor: "green",
    name: "Cox Hall",
    gender: "male",
    company: "ZEAM",
    email: "coxhall@zeam.com",
    phone: "+1 (860) 415-3183",
    address: "951 Channel Avenue, Falmouth, Kentucky, 7602",
    about:
      "Officia magna irure proident excepteur qui dolore duis sunt irure reprehenderit veniam exercitation velit duis. Occaecat enim voluptate aliquip minim enim. Reprehenderit elit id anim adipisicing deserunt incididunt dolore adipisicing nisi fugiat laborum. Tempor magna ipsum sint quis aliqua ullamco laborum id dolor Lorem consequat Lorem amet duis. Fugiat velit id minim eu enim laborum qui sint dolore enim. Adipisicing Lorem et mollit tempor non laboris adipisicing enim veniam pariatur. Proident nostrud elit id aliquip sit.\r\n",
    registered: "2014-07-02T06:51:48 +03:00",
    latitude: 18.498154,
    longitude: -6.229509,
    tags: ["aliqua", "tempor", "qui", "do", "adipisicing", "velit", "nulla"],
    friends: [
      {
        id: 0,
        name: "Gamble Combs",
      },
      {
        id: 1,
        name: "Rosales Graham",
      },
      {
        id: 2,
        name: "Edwina Beach",
      },
    ],
    greeting: "Hello, Cox Hall! You have 8 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "62f2f7e68723d792fba1f8ef",
    index: 1,
    guid: "839a53ee-2825-4f3b-b8f9-623298a53ac2",
    isActive: false,
    balance: "$2,711.66",
    picture: "http://placehold.it/32x32",
    age: 29,
    eyeColor: "green",
    name: "Nell Quinn",
    gender: "female",
    company: "EXOTERIC",
    email: "nellquinn@exoteric.com",
    phone: "+1 (981) 439-2013",
    address: "640 Cypress Avenue, Orason, New York, 8640",
    about:
      "Ipsum consectetur anim reprehenderit amet est aliquip ex laboris nisi. Tempor in labore ad Lorem sint nulla deserunt. Nostrud ex consequat reprehenderit fugiat pariatur eiusmod. Id cillum commodo incididunt esse sit labore velit dolor exercitation reprehenderit veniam laboris sit. Aute incididunt commodo exercitation officia ullamco tempor laborum ea qui nisi reprehenderit sit. Cupidatat nostrud irure consectetur elit. Aute id occaecat ex dolor aute excepteur ex esse.\r\n",
    registered: "2020-02-07T03:23:09 +03:00",
    latitude: -7.836995,
    longitude: 156.402534,
    tags: ["excepteur", "nisi", "esse", "nulla", "est", "elit", "enim"],
    friends: [
      {
        id: 0,
        name: "Townsend Sweeney",
      },
      {
        id: 1,
        name: "Briana Mills",
      },
      {
        id: 2,
        name: "Ruth Prince",
      },
    ],
    greeting: "Hello, Nell Quinn! You have 2 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62f2f7e658f8506469e884f9",
    index: 2,
    guid: "cf6a0351-2ae8-461d-aa6f-f45a2eb24258",
    isActive: false,
    balance: "$3,684.18",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "brown",
    name: "Gay Daugherty",
    gender: "female",
    company: "ICOLOGY",
    email: "gaydaugherty@icology.com",
    phone: "+1 (812) 571-2235",
    address: "629 Brightwater Court, Ola, Mississippi, 7681",
    about:
      "Laboris labore officia duis velit dolore esse ullamco amet magna eiusmod cillum adipisicing veniam. Ex ea anim voluptate adipisicing aliqua non nostrud proident ad. Minim eu adipisicing proident quis ut aliqua sunt. Eiusmod exercitation ullamco irure sit do voluptate. Commodo in amet ipsum nostrud labore.\r\n",
    registered: "2014-09-13T01:48:51 +03:00",
    latitude: 30.999087,
    longitude: -168.289962,
    tags: [
      "reprehenderit",
      "adipisicing",
      "amet",
      "dolor",
      "ad",
      "irure",
      "nisi",
    ],
    friends: [
      {
        id: 0,
        name: "Teresa Potts",
      },
      {
        id: 1,
        name: "Watkins Phillips",
      },
      {
        id: 2,
        name: "Daniel Dejesus",
      },
    ],
    greeting: "Hello, Gay Daugherty! You have 2 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62f2f7e6856bd868e13d79ad",
    index: 3,
    guid: "089bea4c-0d6c-4dad-83ec-7144a6713763",
    isActive: false,
    balance: "$3,470.41",
    picture: "http://placehold.it/32x32",
    age: 27,
    eyeColor: "brown",
    name: "Corinne Hicks",
    gender: "female",
    company: "AMRIL",
    email: "corinnehicks@amril.com",
    phone: "+1 (818) 443-3601",
    address: "439 Charles Place, Jardine, Missouri, 2168",
    about:
      "Ex sunt occaecat ipsum excepteur cillum magna eu aliqua cupidatat enim esse magna labore. Cupidatat labore occaecat ea sint ut mollit. Incididunt proident consectetur aute cillum consectetur reprehenderit aliqua. Nulla aliquip ea tempor sunt. Eu amet nisi deserunt aliquip velit est ex nulla.\r\n",
    registered: "2015-01-30T04:51:00 +03:00",
    latitude: -16.365747,
    longitude: 57.106327,
    tags: ["proident", "laborum", "velit", "aute", "laboris", "enim", "ut"],
    friends: [
      {
        id: 0,
        name: "Marina Perkins",
      },
      {
        id: 1,
        name: "Alison Duran",
      },
      {
        id: 2,
        name: "Russell Stark",
      },
    ],
    greeting: "Hello, Corinne Hicks! You have 1 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "62f2f7e635e80c40163f028f",
    index: 4,
    guid: "ed25b873-6961-4c4d-9487-389e0c62c643",
    isActive: false,
    balance: "$1,916.12",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "brown",
    name: "Bryant Todd",
    gender: "male",
    company: "DOGSPA",
    email: "bryanttodd@dogspa.com",
    phone: "+1 (840) 427-2498",
    address: "645 Conduit Boulevard, Harrison, Marshall Islands, 4994",
    about:
      "Amet esse esse ex ullamco aute culpa officia qui tempor exercitation ut eiusmod ad. Occaecat velit sunt et velit deserunt cillum fugiat aute minim. Voluptate excepteur amet laboris sit.\r\n",
    registered: "2019-06-07T08:16:59 +03:00",
    latitude: -73.786919,
    longitude: -44.970654,
    tags: [
      "aute",
      "exercitation",
      "Lorem",
      "aliquip",
      "excepteur",
      "Lorem",
      "est",
    ],
    friends: [
      {
        id: 0,
        name: "Pickett Pena",
      },
      {
        id: 1,
        name: "Mandy Huffman",
      },
      {
        id: 2,
        name: "Lopez Hopper",
      },
    ],
    greeting: "Hello, Bryant Todd! You have 9 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62f2f7e66c54b76856c5fcf4",
    index: 5,
    guid: "3f70825d-5275-47d2-bb1d-d01986ed2cb6",
    isActive: true,
    balance: "$1,668.44",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "green",
    name: "Celia Koch",
    gender: "female",
    company: "EWAVES",
    email: "celiakoch@ewaves.com",
    phone: "+1 (918) 476-3629",
    address: "689 Homecrest Avenue, Innsbrook, Minnesota, 8251",
    about:
      "Lorem nulla incididunt et magna cillum fugiat voluptate do in sint. Ullamco quis do id incididunt. Excepteur in Lorem eiusmod dolore eu incididunt ad adipisicing anim commodo qui officia voluptate in. Do voluptate ex consequat proident id. Labore laborum cupidatat cillum irure commodo dolore officia laboris fugiat sunt veniam irure commodo. Cupidatat excepteur laborum dolor est occaecat est anim consectetur sit tempor excepteur. Nisi ea culpa excepteur ullamco.\r\n",
    registered: "2017-10-18T11:37:48 +03:00",
    latitude: 34.014169,
    longitude: 128.339973,
    tags: ["ea", "ipsum", "mollit", "ex", "laborum", "eiusmod", "qui"],
    friends: [
      {
        id: 0,
        name: "Malone Solomon",
      },
      {
        id: 1,
        name: "Vanessa Gay",
      },
      {
        id: 2,
        name: "Robin Mccray",
      },
    ],
    greeting: "Hello, Celia Koch! You have 9 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "62f2f7e66292fd155b7a2288",
    index: 6,
    guid: "49af3752-c467-4867-bda6-d10b03e9552c",
    isActive: false,
    balance: "$1,571.62",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "blue",
    name: "Rodgers Wright",
    gender: "male",
    company: "CYCLONICA",
    email: "rodgerswright@cyclonica.com",
    phone: "+1 (980) 551-2866",
    address: "210 Division Place, Gasquet, Colorado, 4967",
    about:
      "Ad labore veniam enim id nulla ipsum esse Lorem duis officia reprehenderit dolore proident nulla. Id veniam exercitation voluptate id qui cupidatat tempor sint. Adipisicing est fugiat in magna ad ex veniam velit. In exercitation laboris irure do. Eiusmod excepteur est excepteur consectetur est velit est cupidatat amet. Reprehenderit elit non irure tempor ex aliqua labore nostrud ea veniam mollit deserunt amet.\r\n",
    registered: "2018-05-26T05:11:01 +03:00",
    latitude: -72.160618,
    longitude: -7.719232,
    tags: ["eu", "eu", "amet", "amet", "labore", "esse", "duis"],
    friends: [
      {
        id: 0,
        name: "Eunice Jefferson",
      },
      {
        id: 1,
        name: "Jeannette Dillard",
      },
      {
        id: 2,
        name: "Edwards Hobbs",
      },
    ],
    greeting: "Hello, Rodgers Wright! You have 9 unread messages.",
    favoriteFruit: "banana",
  },
];
