module.exports = [
  {
    startDate: "08-2022",
    finishDate: "Present",
    company: "Slang",
    location: "Boston, U.S.",
    website: "https://slangapp.com/",
    role: "Growth Engineer",
    mainTech: ["Javascript", "ReactJS"],
  },
  {
    startDate: "07-2020",
    finishDate: "Present",
    company: "Ocean Ring Techonologies",
    location: "Philadelphia, U.S.",
    website: "https://www.oceanring.com/",
    role: "Frontend Developer (Freelancer)",
    mainTech: ["Javascript", "ReactJS", "NEXTjs", "Wordpress"],
  },
  {
    startDate: "12-2021",
    finishDate: "07-2022",
    company: "SIONO",
    location: "Florida, U.S.",
    website: "https://siono.com/",
    role: "Software Engineer",
    mainTech: ["Javascript", "SVELTE", "Firebase"],
  },
  {
    startDate: "11-2020",
    finishDate: "12-2021",
    company: "Aconcagua Software Factory",
    location: "Mendoza, Argentina",
    website: "https://www.aconcaguasoftwarefactory.com/",
    role: "Frontend Developer",
    mainTech: [
      "Javascript",
      "ReactJS",
      "Hooks",
      "React Native",
      "Sass",
      "Material UI",
      "Formik",
    ],
  },
  {
    startDate: "04-2019",
    finishDate: "10-2020",
    company: "Vaypol",
    location: "Mendoza, Argentina",
    website: "https://vaypol.com/",
    role: "Fullstack Developer",
    mainTech: [
      "Ruby",
      "Ruby on Rails",
      "Javascript",
      "Sass",
      "ReactJS",
      "Redux",
      "AWS",
    ],
  },
  {
    startDate: "12-2018",
    finishDate: "03-2019",
    company: "Zamphyr",
    website: "https://zamphyr.com/",
    location: "Tallinn, Estonia",
    role: "Frontend Developer (Intern)",
    mainTech: ["Javascript", "Angular"],
  },
  {
    startDate: "07-2018",
    finishDate: "09-2018",
    company: "Pomelo Web",
    location: "Mendoza, Argentina",
    role: "Web Developer",
    mainTech: ["Javascript", "HTML5", "CSS"],
  },
  {
    startDate: "12-2017",
    finishDate: "04-2018",
    company: "R1 Group",
    location: "Mendoza, Argentina",
    role: "Frontend Developer (Intern)",
    mainTech: ["Javascript", "Angular", "Bootstrap"],
  },
];
